// File generated by flutterfire_cli.
// Ignore changes to this file unless you know what you are doing.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_platform_interface/flutter_platform_interface.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    if (defaultTargetPlatform == TargetPlatform.web) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:android:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
    iosBundleId: 'com.example.smartNotifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:windows:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:linux:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:macos:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
    iosBundleId: 'com.example.smartNotifier.RunnerTests',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyXxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:web:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'smart-notifier-xxxxx',
    storageBucket: 'smart-notifier-xxxxx.appspot.com',
    authDomain: 'smart-notifier-xxxxx.firebaseapp.com',
  );
}
